App\Entity\Membre:
  properties:
    email:
      - NotNull: ~
      - NotBlank: ~

      - Type:
          type: string
          message: The value {{ value }} is not a valid {{ type }}.

      - Length:
          min: 3
          max: 50
          minMessage: "field: email must be at least {{ limit }} characters long"
          maxMessage: "field: email  cannot be longer than {{ limit }} characters"
